version: '3.0'
services:
  mag2_web:
    container_name: mag2_web
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - mag2_db
    env_file:
      - env
  mag2_db:
    container_name: mag2_db
    image: mysql:5.6.23
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  mag2_pma:
    container_name: mag2_pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    volumes:
      - /sessions
    ports:
      - "8580:80"
    links:
      - mag2_db
volumes:
  db-data: